name: github action secrets

on:
    workflow_dispatch:

jobs:
    deployment:
        runs-on: windows-latest
        steps:
            - name: print secret
              run: |
                 echo "MY_TOP_SECRET: ${{ secrets.MY_TOP_SECRET}}"
                 echo "i_dont_exist: ${{ secrets.i_dont_exist}}"

            - name: print secret as environment variable
              run: |
                 echo "MY_TOP_SECRET: $MY_TOP_SECRET"
              env:
                 MY_TOP_SECRET: ${{ secrets.MY_TOP_SECRET}}