name: artifact demo

on:
    push

jobs:
    job_1:
        name: upload artifact
        runs-on: ubuntu-latest
        steps:
            - name: create a local file
              run: echo "Hi, I am the storing this data in this file, so that I can use this in the subsequent jobs within this workflow run. I will upload this file to github storage and download from there when need in this workflow." > file.txt

            - uses: actions/upload-artifact@v3
              with:
                name: file
                path: file.txt
                retention-days: 10


    jobs_2:
        name: download artifact
        runs-on: ubuntu-latest
        needs: job_1
        steps:
           - uses: actions/download-artifact@v2
             with:
               name: file
           - run: cat file.txt
