name: List all defualt GITHUB vars

on:
    workflow_dispatch:
    
jobs:
    ubuntu-environment-varibles:
        runs-on: ubuntu-latest
        steps:
            - run: env

    windows-environment-variables:
        runs-on: windows-latest
        steps:
            - run: env

    macos-environment-variables:
        runs-on: macos-latest
        steps:
            - run: env