name: 'Github workflow demo'
on: 
    workflow_dispatch:
    push:
        branches: ["main"]
    
jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
        - name: runscript-to-say-hello
          run: echo Howdy Github Action

        - uses: actions/checkout@v3