name: passing value to next steps

on: workflow_dispatch

jobs:
    passing-values-bw-steps:
        runs-on: ubuntu-latest
        steps:
            - name: set the vaule ENV vars
              run: |
                 echo "variableName=this-is-value" >> $GITHUB_ENV


            - name: creating variables
              id: var_source_step
              run: |
                  echo "Performance a random task"
                  echo "::set-output name=var1_name::TechSchool"
                  echo "::set-output name=var2_date::$(date+'%Y-%m-%d-%H-%M')"
                  
                  
            - name: get variable values
              run: |
                  echo "Printing the values"
                  echo variableName: ${{ env.variableName }}
                  echo var1_name: ${{ steps.var_source_step.outputs.var1_name }}
                  echo var2_date: ${{ steps.var_source_step.outputs.var2_date }}