# This is a workflow to demonstrate self hosted runner job processing

name: self hosted runner demo

on: workflow_dispatch

jobs:
    hello-self-hosted-runner:
        runs-on: [self-hosted, Windows, X64, gpu]
        steps:
            
            - name: sleep for 100 seconds
              run: sleep 100
